theme: jekyll-theme-dinky
markdown: CommonMarkGhPages
title: John Bamberg
description: " "

header_pages:
  - index.md
  - about.md
  - publications.md
  - teaching.md
  - supervision.md
  - software.md
  - errata.md