theme: minima
markdown: kramdown
title: John Bamberg
description: " "
header_pages:
  - index.md
  - about.md
  - publications.md
  - teaching.md
  - supervision.md
  - software.md
  - errata.md
kramdown:
  math_engine: mathjax
